#!/bin/sh
#
# Usage: odf-replace <document> <string-to-replace> <string-replacement> [xml-file]
# Tested with OpenOffice.org 3.x and LibreOffice 3.{3,4}
#
# Substitutes all occurrences of a string by another in the given ODF document
#
# xml-file is the part of the document archive the substitution is run on
# (content.xml by default)
#
# Copyright (C) 2010-2012 Free Electrons
# Author: Michael Opdenacker <michael at free-electrons com>
# Home page: http://git.free-electrons.com/training-scripts/
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
# 
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
# NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
# USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# You should have received a copy of the  GNU General Public License along
# with this program; if not, write  to the Free Software Foundation, Inc.,
# 675 Mass Ave, Cambridge, MA 02139, USA.


DOC=$1
SOURCE=$2
REPLACEMENT=$3
XMLFILE=$4

if [ "$XMLFILE" = "" ]
then
	XMLFILE=content.xml
fi

FILENAME=`basename $DOC`
TMP=odf-replace.tmp
NEW=modified.zip

# Extract the document

/bin/rm -rf $TMP
mkdir -p $TMP
cp -f $DOC $TMP
cd $TMP
/usr/bin/unzip -q $FILENAME
rm $FILENAME

# Make the substitution

if [ ! -f $XMLFILE ]
then
	echo "ERROR: missing $XMLFILE file in document archive. Aborting."
	exit 1
fi

cat $XMLFILE | sed "s|$SOURCE|$REPLACEMENT|g" > tmpnew.xml
mv -f tmpnew.xml $XMLFILE

# Rebuild the archive

rm -f ../$NEW
zip --quiet -r ../$NEW .
cd ..
mv -f $NEW $DOC

# Cleanup

/bin/rm -rf $TMP
